name: Build and Deploy Scala.js

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Scala
        uses: olafurpg/setup-scala@v12
        with:
          java-version: "11"

      - name: Install sbt
        run: |
          curl -L https://github.com/sbt/sbt/releases/download/v1.8.3/sbt-1.8.3.tgz | tar xz
          echo "$PWD/sbt/bin" >> $GITHUB_PATH

      - name: Copiar index.html al directorio de salida
        run: cp src/main/resources/index.html target/scala-3.3.3/

      - name: Compile Scala.js
        run: sbt fastLinkJS

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/scala-3.3.3

